'use client'
import './globals.css'

import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Script from 'next/script'
import Header from '@/components/Header'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const localStoragename = 'loginCredentials'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [loginDetails, loginUpdater] = useState(false)
  // const [loginDetails, loginUpdater] = useState({ _id: "kunal", username: "admin" });
  const setLoginDetails = (data: any) => {
    try {
      // used for login as well as logout
      loginUpdater(data)
      if (data) {
        data['expired'] = new Date().getTime() + 1000 * 60 * 60 * 24
        localStorage.setItem(localStoragename, JSON.stringify(data))
      } else {
        localStorage.removeItem(localStoragename)
      }
    } catch (err) {
      console.error(err)
    }
  }

  useEffect(() => {
    try {
      let data = localStorage.getItem(localStoragename) as any
      if (data) {
        data = JSON.parse('' + data)
        if (!data.conn) {
          localStorage.removeItem(localStoragename)
          alert(
            'please re-login, we are upgrading our services.\nIf issue arrive, please wait'
          )
          return
        }
        loginUpdater(data)
      }
    } catch (err) {
      console.error(err)
    }
  }, [])
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <link rel="stylesheet" href="/css/open-iconic-bootstrap.min.css" />
        <link rel="stylesheet" href="/css/animate.css" />
        <link rel="stylesheet" href="/css/owl.carousel.min.css" />
        <link rel="stylesheet" href="/css/owl.theme.default.min.css" />
        <link rel="stylesheet" href="/css/magnific-popup.css" />
        <link rel="stylesheet" href="/css/aos.css" />
        <link rel="stylesheet" href="/css/ionicons.min.css" />
        <link rel="stylesheet" href="/css/flaticon.css" />
        <link rel="stylesheet" href="/css/icomoon.css" />
        <link rel="stylesheet" href="/css/style.css" />
      </head>
      <body>
        <Header user={loginDetails} userUpdate={setLoginDetails} />
        {children}
      </body>
      <script async src="/js/jquery.min.js"></script>
      <script async src="/js/jquery-migrate-3.0.1.min.js"></script>
      <script async src="/js/popper.min.js"></script>
      <script async src="/js/bootstrap.min.js"></script>
      <script async src="/js/jquery.easing.1.3.js"></script>
      <script async src="/js/jquery.waypoints.min.js"></script>
      <script async src="/js/jquery.stellar.min.js"></script>
      <script async src="/js/owl.carousel.min.js"></script>
      <script async src="/js/jquery.magnific-popup.min.js"></script>
      <script async src="/js/aos.js"></script>
      <script async src="/js/jquery.animateNumber.min.js"></script>
      <script async src="/js/scrollax.min.js"></script>
      <script async src="/js/main.js"></script>
      <div id="ftco-loader" className="show fullscreen">
        <svg className="circular" width="48px" height="48px">
          <circle
            className="path-bg"
            cx="24"
            cy="24"
            r="22"
            fill="none"
            strokeWidth="4"
            stroke="#eeeeee"
          />
          <circle
            className="path"
            cx="24"
            cy="24"
            r="22"
            fill="none"
            strokeWidth="4"
            strokeMiterlimit="10"
            stroke="#F96D00"
          />
        </svg>
      </div>
    </html>
  )
}
